version: '3.5'

services:
  backend:
    container_name: api_dacs
    image: docker/getting-started
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=nqnphuong
      - DB_PASSWORD=dnport
    ports:
      - "5000:5000"
    networks:
      - postgres
    volumes:
      - /backend:/data/backend
    depends_on:
      - postgres
      - pgadmin
    restart: on-failure

  postgres:
    container_name: postgres_dacs
    image: postgres
    environment:
      POSTGRES_USER: nqnphuong
      POSTGRES_PASSWORD: dnport
      PGDATA: /data/postgres
    volumes:
#      - /postgres:/data/postgres
      - ${DATA_SAVE_PATH}/postgres:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: on-failure

  pgadmin:
    container_name: pgadmin_dacs
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "1080:80"
    networks:
      - postgres
    restart: on-failure

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
    backend:
